spring:
  config:
    import: optional:classpath:config/common/application.yaml

---

server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/now-start/config-service
          search-paths: src/main/resources/config/*

encrypt:
  key: ${ENCRYPT_KEY}