server:
  shutdown: graceful
  forward-headers-strategy: framework

spring:
  jmx:
    enabled: true

encrypt:
  key: '{cipher}27c52131842a4d1aa2fe34746cb0afed88c973d4e7dab7c55dacea98f1619c93'

eureka:
  instance:
    metadata-map:
      management.port: ${management.server.port}
  client:
    service-url:
      defaultZone: '{cipher}03514cd71ba8d49b353cdc127791adaec3604e83d69d1d22e8de5def04a9bb5345b8adc8b1a5ea3572d1323715cbb84a'

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
    access:
      default: unrestricted
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
  info:
    os:
      enabled: true
    java:
      enabled: true
    process:
      enabled: true

otel:
  exporter:
    otlp:
      endpoint: '{cipher}0c1ba71e78b809e8ef24e132beb02fce505e327046a8a8df0def7f654a8deb10085b2cdbafe37a57c514dcd47023117a'

logging:
  charset:
    file: UTF-8
  file:
    path: ./logs
  logback:
    rollingpolicy:
      max-history: 7
