version = '2.11.3'

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.cloud:spring-cloud-starter-config'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    implementation 'de.codecentric:spring-boot-admin-starter-server'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui'
}
