name: Platform CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types:
      - released
      - prereleased
      - edited

permissions:
  contents: write
  packages: write

jobs:
  config:
    uses: now-start/workflow/.github/workflows/reusable-java-app.yaml@main
    with:
      module: config
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}

  eureka:
    uses: now-start/workflow/.github/workflows/reusable-java-app.yaml@main
    with:
      module: eureka
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}

  admin:
    uses: now-start/workflow/.github/workflows/reusable-java-app.yaml@main
    with:
      module: admin
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}

  gateway:
    uses: now-start/workflow/.github/workflows/reusable-java-app.yaml@main
    with:
      module: gateway
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
